Repository PappasBrent/maki, pull requests merged in 2024-04, with the labels that each got.

#20 Change Clang plugin output to JSON
  src/Cpp2CASTConsumer.cc
Labels: Task

#23 Shorten "PATCH" file names for linux patch submissions in the accepte…
  README.md
  datasets/linux_patch_submissions/accepted/PATCH_Ref_1.mbox
  datasets/linux_patch_submissions/accepted/PATCH_Ref_2.mbox
  datasets/linux_patch_submissions/accepted/PATCH_Ref_3.mbox
  datasets/linux_patch_submissions/accepted/PATCH_Ref_4.mbox
  datasets/linux_patch_submissions/accepted/PATCH_Ref_5.mbox
  datasets/linux_patch_submissions/accepted/PATCH_Ref_6.mbox
  datasets/linux_patch_submissions/rejected/PATCH_Ref_7.mbox
  datasets/linux_patch_submissions/rejected/PATCH_Ref_8.mbox
Labels: Feature

#22 output changed csv to json
  .gitignore
  evaluation/get_figure_2_data.py
  evaluation/get_figure_3_data.py
  evaluation/get_figure_4_data.py
  evaluation/tabulate_analyses.py
Labels: Task

#25 Feature/modify filenames and code to use and produce shorter filenames for source n program files
  src/CMakeLists.txt
  src/Cpp2CASTConsumer.cc
  src/MacroExpansionArg.cc
  src/MacroExpansionArg.hh
  src/MacroExpansionNode.hh
  src/MacroForest.cc
Labels: Feature

#26 Filenames and corresponding references shortened for DefinitionInfoCollector code and header files
  src/CMakeLists.txt
  src/Cpp2CASTConsumer.cc
  src/Cpp2CASTConsumer.hh
  src/DefnInfoCollector.cc
  src/DefnInfoCollector.hh
Labels: Feature

#27 Bugfix results replication
  evaluation/analyze_macro_definitions_in_program.py
  evaluation/analyze_macro_invocations_in_programs.py
  evaluation/get_figure_2_data.py
  evaluation/get_figure_3_data.py
  evaluation/get_figure_4_data.py
  evaluation/macros.py
  replicate_results.sh
Labels: Bug-Fix

#28 Final changes to shorten filenames. This change shortens filenames and references using the word "definition" or "definitions" to "defn" or "defns".
  README.md
  datasets/time_data/defn_analysis_times.csv
  evaluation/analyze_macro_defns_in_program.py
  evaluation/analyze_macro_defns_in_programs.py
  evaluation/analyze_times.py
  replicate_results.sh
Labels: Feature
